name: style-transfer

on: [push]

jobs:
  run:
    runs-on: [self-hosted]
    container: 
      image: docker://dvcorg/cml-gpu-py3:latest
      options: --runtime "nvidia" -e NVIDIA_VISIBLE_DEVICES=all

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get install python3-dev -y
          apt install imagemagick -y
          pip install -r requirements.txt
          pip install dvc
          dvc repro
          
          echo "# Style transfer" >> report.md
          git show origin/master:final_owl.png > master_owl.png
          convert +append final_owl.png master_owl.png out.png
          echo "### Workspace vs. Master" >> report.md
          cml-publish out.png --md --title 'compare' >> report.md
          
          echo "## Training metrics" >> report.md
          git fetch --prune --unshallow
          dvc params diff master --show-md >> report.md
          
          echo >> report.md
          echo "## GPU info" >> report.md
          cat gpu_info.txt >> report.md
          
          cml-send-comment report.md 

          
